import type { JurisdictionDef } from "./types";

/**
 * The 50 states + DC. Agency directory data (office name, official website, business
 * search, periodic report name) was gathered from official government sites on
 * 2026-09-27 — see docs/research/. "verified" means the agency website itself was
 * fetched and confirmed as the official site.
 *
 * This is a DIRECTORY ONLY. No filing rules (due dates, fees) exist for a state
 * unless it has entries in the rules registry; every other state is treated as
 * UNVERIFIED and the product makes no definitive claims about it.
 */
export const JURISDICTIONS: JurisdictionDef[] = [
  {
    code: "AL",
    name: "Alabama",
    slug: "alabama",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Alabama Secretary of State, Business Entities Division",
      websiteUrl: "https://www.sos.alabama.gov/business-entities",
      businessSearchUrl: "https://arc-sos.state.al.us/CGI/CORPNAME.MBR/INPUT",
      periodicReportName: null,
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "AK",
    name: "Alaska",
    slug: "alaska",
    timezone: "America/Anchorage",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Alaska Department of Commerce, Community, and Economic Development, Division of Corporations, Business and Professional Licensing (Corporations Section)",
      websiteUrl: "https://www.commerce.alaska.gov/web/cbpl/Corporations.aspx",
      businessSearchUrl: "https://www.commerce.alaska.gov/cbp/main/search/entities",
      periodicReportName: "Biennial Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "AZ",
    name: "Arizona",
    slug: "arizona",
    timezone: "America/Phoenix",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Arizona Corporation Commission, Corporations Division (Business Services)",
      websiteUrl: "https://azcc.gov/corporations/home",
      businessSearchUrl: "https://arizonabusinesscenter.azcc.gov/businesssearch",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "AR",
    name: "Arkansas",
    slug: "arkansas",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Arkansas Secretary of State, Business & Commercial Services (BCS) Division",
      websiteUrl: "https://www.sos.arkansas.gov/business-commercial-services-bcs",
      businessSearchUrl: "https://www.sos.arkansas.gov/corps/search_all.php",
      periodicReportName: "Franchise Tax / Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "CA",
    name: "California",
    slug: "california",
    timezone: "America/Los_Angeles",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "California Secretary of State, Business Programs Division",
      websiteUrl: "https://www.sos.ca.gov/business-programs",
      businessSearchUrl: "https://bizfileonline.sos.ca.gov/search/business",
      periodicReportName: "Statement of Information",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "CO",
    name: "Colorado",
    slug: "colorado",
    timezone: "America/Denver",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Colorado Secretary of State, Business and Licensing Division (Business Organizations)",
      websiteUrl: "https://www.coloradosos.gov/pubs/business/businessHome.html",
      businessSearchUrl: "https://www.coloradosos.gov/biz/BusinessEntityCriteriaExt.do",
      periodicReportName: "Periodic Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "CT",
    name: "Connecticut",
    slug: "connecticut",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Connecticut Secretary of the State, Business Services Division",
      websiteUrl: "https://business.ct.gov/",
      businessSearchUrl: "https://service.ct.gov/business/s/onlinebusinesssearch?language=en_US",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "DE",
    name: "Delaware",
    slug: "delaware",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Delaware Department of State, Division of Corporations",
      websiteUrl: "https://corp.delaware.gov/",
      businessSearchUrl: "https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx",
      periodicReportName: "Annual Franchise Tax Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "DC",
    name: "District of Columbia",
    slug: "district-of-columbia",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "DC Department of Licensing and Consumer Protection (DLCP), Business and Professional Licensing Administration, Corporations Division",
      websiteUrl: "https://dlcp.dc.gov/page/corporations-0",
      businessSearchUrl: "https://boss.dc.gov/homepage/business-license-search",
      periodicReportName: "Biennial Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "FL",
    name: "Florida",
    slug: "florida",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Florida Department of State, Division of Corporations (Sunbiz)",
      websiteUrl: "https://dos.fl.gov/sunbiz/",
      businessSearchUrl: "https://search.sunbiz.org/Inquiry/CorporationSearch/ByName",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "GA",
    name: "Georgia",
    slug: "georgia",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Georgia Secretary of State, Corporations Division",
      websiteUrl: "https://sos.ga.gov/corporations-division-georgia-secretary-states-office",
      businessSearchUrl: "https://ecorp.sos.ga.gov/BusinessSearch",
      periodicReportName: "Annual Registration",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "HI",
    name: "Hawaii",
    slug: "hawaii",
    timezone: "Pacific/Honolulu",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Hawaii Department of Commerce and Consumer Affairs (DCCA), Business Registration Division (BREG)",
      websiteUrl: "https://cca.hawaii.gov/breg/",
      businessSearchUrl: "https://hbe.dcca.hawaii.gov/search-and-buy",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "ID",
    name: "Idaho",
    slug: "idaho",
    timezone: "America/Boise",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Idaho Secretary of State, Business Services Division",
      websiteUrl: "https://sos.idaho.gov/business-services/",
      businessSearchUrl: "https://sosbiz.idaho.gov/search/business",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "IL",
    name: "Illinois",
    slug: "illinois",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Illinois Secretary of State, Department of Business Services",
      websiteUrl: "https://www.ilsos.gov/departments/business-services.html",
      businessSearchUrl: "https://apps.ilsos.gov/businessentitysearch/",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "IN",
    name: "Indiana",
    slug: "indiana",
    timezone: "America/Indiana/Indianapolis",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Indiana Secretary of State, Business Services Division",
      websiteUrl: "https://www.in.gov/sos/business/",
      businessSearchUrl: "https://bsd.sos.in.gov/publicbusinesssearch",
      periodicReportName: "Business Entity Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "IA",
    name: "Iowa",
    slug: "iowa",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Iowa Secretary of State, Business Services Division",
      websiteUrl: "https://sos.iowa.gov/business-services",
      businessSearchUrl: "https://sos.iowa.gov/search/business/search.aspx",
      periodicReportName: "Biennial Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "KS",
    name: "Kansas",
    slug: "kansas",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Kansas Secretary of State, Business Services Division",
      websiteUrl: "https://www.sos.ks.gov/businesses/businesses.html",
      businessSearchUrl: "https://www.sos.ks.gov/eforms/BusinessEntity/Search.aspx",
      periodicReportName: "Information Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "KY",
    name: "Kentucky",
    slug: "kentucky",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Kentucky Secretary of State - Business Filings",
      websiteUrl: "https://www.sos.ky.gov/bus/business-filings/Pages/default.aspx",
      businessSearchUrl: "https://sosbes.sos.ky.gov/BusSearchNProfile/search.aspx",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "LA",
    name: "Louisiana",
    slug: "louisiana",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Louisiana Secretary of State - Commercial Division (Business Services)",
      websiteUrl: "https://www.sos.la.gov/business-services",
      businessSearchUrl: "https://coraweb.sos.la.gov/CommercialSearch/CommercialSearch.aspx",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "ME",
    name: "Maine",
    slug: "maine",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Maine Secretary of State - Division of Corporations, UCC & Commissions (Bureau of Corporations, Elections & Commissions), Corporations-Business Services",
      websiteUrl: "https://www.maine.gov/sos/corporations-commissions/corporations-business-services",
      businessSearchUrl: "https://apps3.web.maine.gov/nei-sos-icrs/ICRS?MainPage=x",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "MD",
    name: "Maryland",
    slug: "maryland",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Maryland State Department of Assessments and Taxation (SDAT) - Charter Division / Charter Business Services",
      websiteUrl: "https://dat.maryland.gov/businesses/Pages/default.aspx",
      businessSearchUrl: "https://egov.maryland.gov/BusinessExpress/EntitySearch",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "MA",
    name: "Massachusetts",
    slug: "massachusetts",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Secretary of the Commonwealth of Massachusetts - Corporations Division",
      websiteUrl: "https://www.sec.state.ma.us/divisions/corporations/corporations.htm",
      businessSearchUrl: "https://corp.sec.state.ma.us/corpweb/CorpSearch/CorpSearch.aspx",
      periodicReportName: "Annual Report",
      verificationStatus: "unverified",
      lastVerifiedAt: null,
    },
  },
  {
    code: "MI",
    name: "Michigan",
    slug: "michigan",
    timezone: "America/Detroit",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Michigan Department of Licensing and Regulatory Affairs (LARA) - Corporations, Securities & Commercial Licensing Bureau, Corporations Division",
      websiteUrl: "https://www.michigan.gov/lara/bureau-list/cscl/corps",
      businessSearchUrl: "https://mibusinessregistry.lara.state.mi.us/search/business",
      periodicReportName: "Annual Report / Annual Statement",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "MN",
    name: "Minnesota",
    slug: "minnesota",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Minnesota Secretary of State - Business & Liens (Business Services)",
      websiteUrl: "https://www.sos.mn.gov/business-liens/",
      businessSearchUrl: "https://mblsportal.sos.mn.gov/Business/Search",
      periodicReportName: "Annual Renewal",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "MS",
    name: "Mississippi",
    slug: "mississippi",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Mississippi Secretary of State - Business Services & External Affairs Division",
      websiteUrl: "https://www.sos.ms.gov/business-services-external-affairs",
      businessSearchUrl: "https://corp.sos.ms.gov/corp/portal/c/page/corpBusinessIdSearch/portal.aspx",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "MO",
    name: "Missouri",
    slug: "missouri",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Missouri Secretary of State - Business Services Division (Corporations Unit)",
      websiteUrl: "https://www.sos.mo.gov/business",
      businessSearchUrl: "https://bsd.sos.mo.gov/BusinessEntity/BESearch.aspx?SearchType=0",
      periodicReportName: "Annual or Biennial Registration Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "MT",
    name: "Montana",
    slug: "montana",
    timezone: "America/Denver",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Montana Secretary of State - Business Services (Business & UCC Services)",
      websiteUrl: "https://sosmt.gov/business/",
      businessSearchUrl: "https://biz.sosmt.gov/search/business",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "NE",
    name: "Nebraska",
    slug: "nebraska",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Nebraska Secretary of State - Business Services Division",
      websiteUrl: "https://sos.nebraska.gov/business-services/business-services-division",
      businessSearchUrl: "https://www.nebraska.gov/sos/corp/corpsearch.cgi?nav=search",
      periodicReportName: "Biennial Report / Biennial Occupation Tax Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "NV",
    name: "Nevada",
    slug: "nevada",
    timezone: "America/Los_Angeles",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Nevada Secretary of State - Commercial Recordings Division",
      websiteUrl: "https://bizhub.nv.gov/",
      businessSearchUrl: "https://orion.nv.gov/portal/public/#/public/nvsos/en/CaseXscreen?screen=external-GenericFilingsSearch&tabRoute=business",
      periodicReportName: "Annual List",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "NH",
    name: "New Hampshire",
    slug: "new-hampshire",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "New Hampshire Secretary of State - Corporation Division",
      websiteUrl: "https://www.sos.nh.gov/corporations-0",
      businessSearchUrl: "https://quickstart.sos.nh.gov/online/Account/LandingPage",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "NJ",
    name: "New Jersey",
    slug: "new-jersey",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "New Jersey Department of the Treasury - Division of Revenue and Enterprise Services (DORES)",
      websiteUrl: "https://www.nj.gov/treasury/revenue/",
      businessSearchUrl: "https://www.njportal.com/DOR/BusinessNameSearch/Search/BusinessName",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "NM",
    name: "New Mexico",
    slug: "new-mexico",
    timezone: "America/Denver",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "New Mexico Secretary of State - Business Services Division",
      websiteUrl: "https://www.sos.nm.gov/business-services/",
      businessSearchUrl: "https://enterprise.sos.nm.gov/search/business",
      periodicReportName: "Biennial Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "NY",
    name: "New York",
    slug: "new-york",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "New York Department of State - Division of Corporations, State Records and Uniform Commercial Code",
      websiteUrl: "https://dos.ny.gov/division-corporations-state-records-and-uniform-commercial-code",
      businessSearchUrl: "https://apps.dos.ny.gov/publicInquiry/",
      periodicReportName: "Biennial Statement",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "NC",
    name: "North Carolina",
    slug: "north-carolina",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "North Carolina Department of the Secretary of State - Business Registration Division",
      websiteUrl: "https://www.sosnc.gov/divisions/business_registration",
      businessSearchUrl: "https://www.sosnc.gov/online_services/search/by_title/search_Business_Registration",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "ND",
    name: "North Dakota",
    slug: "north-dakota",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "North Dakota Secretary of State - Business Services",
      websiteUrl: "https://www.sos.nd.gov/business/business-services",
      businessSearchUrl: "https://firststop.sos.nd.gov/search/business",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "OH",
    name: "Ohio",
    slug: "ohio",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Ohio Secretary of State - Business Services Division",
      websiteUrl: "https://www.ohiosos.gov/businesses/",
      businessSearchUrl: null,
      periodicReportName: null,
      verificationStatus: "unverified",
      lastVerifiedAt: null,
    },
  },
  {
    code: "OK",
    name: "Oklahoma",
    slug: "oklahoma",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Oklahoma Secretary of State - Business Filing Department",
      websiteUrl: "https://www.sos.ok.gov/business/default.aspx",
      businessSearchUrl: "https://www.sos.ok.gov/corp/corpInquiryFind.aspx",
      periodicReportName: "Annual Certificate",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "OR",
    name: "Oregon",
    slug: "oregon",
    timezone: "America/Los_Angeles",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Oregon Secretary of State - Corporation Division",
      websiteUrl: "https://sos.oregon.gov/business/Pages/default.aspx",
      businessSearchUrl: "https://egov.sos.state.or.us/br/pkg_web_name_srch_inq.login",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "PA",
    name: "Pennsylvania",
    slug: "pennsylvania",
    timezone: "America/New_York",
    supportLevel: "manual",
    filingEnabled: true,
    agency: {
      name: "Pennsylvania Department of State - Bureau of Corporations and Charitable Organizations",
      websiteUrl: "https://www.pa.gov/agencies/dos/programs/business",
      businessSearchUrl: "https://file.dos.pa.gov/search/business",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "RI",
    name: "Rhode Island",
    slug: "rhode-island",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Rhode Island Department of State - Business Services Division",
      websiteUrl: "https://www.sos.ri.gov/divisions/business-services",
      businessSearchUrl: "https://business.sos.ri.gov/CorpWeb/CorpSearch/CorpSearch.aspx",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "SC",
    name: "South Carolina",
    slug: "south-carolina",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "South Carolina Secretary of State - Business Filings Division",
      websiteUrl: "https://sos.sc.gov/online-filings/business-entities",
      businessSearchUrl: "https://businessfilings.sc.gov/BusinessFiling/Entity/Search",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "SD",
    name: "South Dakota",
    slug: "south-dakota",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "South Dakota Secretary of State - Business Services Division",
      websiteUrl: "https://sdsos.gov/business-services/",
      businessSearchUrl: "https://sosenterprise.sd.gov/BusinessServices/Business/FilingSearch.aspx",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "TN",
    name: "Tennessee",
    slug: "tennessee",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Tennessee Secretary of State - Division of Business and Charitable Organizations",
      websiteUrl: "https://sos.tn.gov/businesses",
      businessSearchUrl: "https://tncab.tnsos.gov/business-entity-search",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "TX",
    name: "Texas",
    slug: "texas",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Texas Secretary of State - Business and Government Filings Division",
      websiteUrl: "https://www.sos.state.tx.us/corp/index.shtml",
      businessSearchUrl: "https://www.sos.state.tx.us/corp/sosda/index.shtml",
      periodicReportName: "Franchise Tax Report / Public Information Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "UT",
    name: "Utah",
    slug: "utah",
    timezone: "America/Denver",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Utah Department of Commerce - Division of Corporations & Commercial Code",
      websiteUrl: "https://commerce.utah.gov/corporations/",
      businessSearchUrl: "https://businessregistration.utah.gov/",
      periodicReportName: "Annual Report/Renewal",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "VT",
    name: "Vermont",
    slug: "vermont",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Vermont Secretary of State - Business Services Division",
      websiteUrl: "https://sos.vermont.gov/business-services",
      businessSearchUrl: "https://bizfilings.vermont.gov/business/businesssearch",
      periodicReportName: "Annual Report / Biennial Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "VA",
    name: "Virginia",
    slug: "virginia",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Virginia State Corporation Commission - Office of the Clerk",
      websiteUrl: "https://www.scc.virginia.gov/businesses/",
      businessSearchUrl: "https://cis.scc.virginia.gov/EntitySearch/Index",
      periodicReportName: "Annual Report / Annual Registration Fee",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "WA",
    name: "Washington",
    slug: "washington",
    timezone: "America/Los_Angeles",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Washington Secretary of State - Corporations & Charities Division",
      websiteUrl: "https://www.sos.wa.gov/corporations-charities",
      businessSearchUrl: "https://ccfs.sos.wa.gov/#/AdvancedSearch",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "WV",
    name: "West Virginia",
    slug: "west-virginia",
    timezone: "America/New_York",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "West Virginia Secretary of State - Business Division",
      websiteUrl: "https://sos.wv.gov/business",
      businessSearchUrl: "https://apps.sos.wv.gov/business/corporations/",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "WI",
    name: "Wisconsin",
    slug: "wisconsin",
    timezone: "America/Chicago",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Wisconsin Department of Financial Institutions - Division of Corporate & Consumer Services",
      websiteUrl: "https://dfi.wi.gov/Pages/BusinessServices/BusinessEntities/GeneralInformation.aspx",
      businessSearchUrl: "https://apps.dfi.wi.gov/apps/corpsearch/search.aspx",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
  {
    code: "WY",
    name: "Wyoming",
    slug: "wyoming",
    timezone: "America/Denver",
    supportLevel: "unsupported",
    filingEnabled: false,
    agency: {
      name: "Wyoming Secretary of State - Business Division",
      websiteUrl: "https://sos.wyo.gov/Business/Default.aspx",
      businessSearchUrl: "https://wyobiz.wyo.gov/Business/FilingSearch.aspx",
      periodicReportName: "Annual Report",
      verificationStatus: "verified",
      lastVerifiedAt: "2026-09-27",
    },
  },
];
